#!/bin/bash

case $1 in
  config)
    cat <<'EOM'
graph_title CPU Frequency
graph_vlabel CPU Frequency
freq.label scaling_cur_freq
EOM
    exit 0;;
esac

echo -n "freq.value "
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
